//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracModel()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int model_id { get; set; }
        public int arac_id { get; set; }
        public string model_adi { get; set; }
        public string model_plaka { get; set; }
        public string model_seri { get; set; }
        public string model_renk { get; set; }
        public string model_km { get; set; }
        public int model_yakit { get; set; }
        public string model_fiyat { get; set; }
        public string model_resim { get; set; }
        public Nullable<bool> model_durum { get; set; }
    
        public virtual AracMarka AracMarka { get; set; }
        public virtual Yakit Yakit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
