//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int satis_id { get; set; }
        public int müsteri_id { get; set; }
        public int model_id { get; set; }
        public string satis_ehliyet { get; set; }
        public string satis_ehliyetTarih { get; set; }
        public string satis_ehliyetVerYeri { get; set; }
        public string satis_kiratip { get; set; }
        public Nullable<System.DateTime> satis_verilis { get; set; }
        public Nullable<System.DateTime> satis_alis { get; set; }
        public Nullable<int> satis_gun { get; set; }
        public Nullable<int> satis_kira { get; set; }
        public Nullable<int> satis_toplam { get; set; }
    
        public virtual AracModel AracModel { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
